---
# tasks file for authenticating.bgp.peerings
 - name: Configure access-list for vty lines
   
   ios_config:
    src: ./roles/authenticating.bgp.peerings/files/r1.txt
    save_when: modified
   ignore_errors: yes
