---
 - name: Copy Lab to Lab Directory
   hosts: localhost
   connection: local
   gather_facts: False
   become: yes
   tasks:
    - name: Copy Lab
      copy:
       src: ../labs/INE_CCIE.unl
       dest: /opt/unetlab/labs/INE_CCIE.unl
       
    - name: Update /etc/hosts
      lineinfile:
        path: /etc/hosts
        create: yes
        state: present
        insertafter: EOF
        block: |
          r1 192.168.1.101
          r2 192.168.1.102
          r3 192.168.1.103
          r4 192.168.1.104
          r5 192.168.1.105
          r6 192.168.1.106
          r7 192.168.1.107
          r8 192.168.1.108
          r9 192.168.1.109
          r10 192.168.1.110
          sw1 192.168.1.111
          sw2 192.168.1.112
          sw3 192.168.1.113
          sw4 192.168.1.114