---
cisco_vty_acl_host:
  - 192.168.1.11
  - 192.168.1.12
  - 192.168.1.13
  - 102.168.1.14

cisco_network_users:
  - net_user: cisco
    net_pass: cisco
  - net_user: admin
    net_pass: admin123
  - net_user: newcreds
    net_pass: newcreds123