---
# vars file for cisco-ios

ansible_network_os: ios
ansible_connection: network_cli
ansible_user: admin123
ansible_password: !vault |
                  $ANSIBLE_VAULT;1.1;AES256
                  63306132363066633638326237353565313865316132633431313631326433333334653336656562
                  3339633035326363396638353835353238386133663763380a363765386133316264643035653762
                  62663431643838626162353565373465323233313865383964336234643934383137613931313564
                  3739353763356661620a623333353364306635383834656438303837343766613761386238663831
                  6634
