---
# tasks file for cisco-ios

# tasks file for cisco-ios

- name: Configure access-list for vty lines
  ios_config:
   src: ./roles/cisco-ios/templates/base_template.j2
   running_config:
   save_when: modified
  ignore_errors: yes
